### ISSUE TITLE
plurilize vs pluralize

### ISSUE THREAD

**Issue by flcdrg** [chrisgalvan/jest-standard-reporter#2]
Looks like a typo, which is possibly the cause of the following error:

```
TypeError: pluralize is not a function

  at getSnapshotStatus (node_modules/jest-standard-reporter/src/getSnapshotStatus.js:32:29)
  at StandardReporter.onTestResult (node_modules/jest-standard-reporter/src/jestStandardReporter.js:74:32)
  at node_modules/@jest/core/build/ReporterDispatcher.js:93:29
  at asyncGeneratorStep (node_modules/@jest/core/build/ReporterDispatcher.js:10:24)
  at _next (node_modules/@jest/core/build/ReporterDispatcher.js:30:9)
  at node_modules/@jest/core/build/ReporterDispatcher.js:35:7
  at node_modules/@jest/core/build/ReporterDispatcher.js:27:12
  at ReporterDispatcher.onTestResult (node_modules/@jest/core/build/ReporterDispatcher.js:113:7)
```

**Comment by flcdrg** [comment]
Confirmed that error is now fixed 👍
