### ISSUE TITLE
TypeError: getConsoleOutput is not a function

### ISSUE THREAD

**Issue by mintyowl** [chrisgalvan/jest-standard-reporter#52]
Hi,

While running with latest @jest version, I get this error

```
 TypeError: getConsoleOutput is not a function

      at getResultHeader (node_modules/jest-standard-reporter/src/getResultHeader.js:58:7)
      at StandardReporter.onTestResult (node_modules/jest-standard-reporter/src/jestStandardReporter.js:58:9)
      at ReporterDispatcher.onTestFileResult (node_modules/@jest/core/build/ReporterDispatcher.js:50:24)
      at async onResult (node_modules/@jest/core/build/TestScheduler.js:195:7)
```
Switching from

`const { getConsoleOutput } = require('jest-util');`

to

`const { getConsoleOutput } = require('@jest/console');`

fixes the problem.

**Comment by chrisgalvan** [comment]
Thanks for reporting the issue @mintyowl. I saw that the `getConsoleOutput` function was moved to a different package. I published a new version to npm. Could you verify if that fixes your issue?

**Comment by mintyowl** [comment]
This does fix the issue I had, thanks!
